name: CMake

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies on Ubuntu
      run: |
        sudo apt-get update
        sudo apt install geographiclib-tools
        #https://downloads.sourceforge.net/project/geographiclib/distrib/GeographicLib-1.52.tar.gz?ts=gAAAAABh6I---TO3Eh2BU6XvrMotvm1_GAPd332ui0BhMmn69hcaWNaNRZGpezL-U155Bhi4ve-A59yNPpHRJWhQlwMUwNNUEQ%3D%3D&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fgeographiclib%2Ffiles%2Flatest%2Fdownload
        #tar xfpz GeographicLib-1.52.tar.gz
        #mkdir BUILD
        #cd BUILD 
        #../configure 
        #make
        #make install
        
        sudo apt-get install libcrypto++-dev libcrypto++-doc libcrypto++-utils
        sudo apt-get install libboost-all-dev
        
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      
      run: 
        cmake --version
        sudo ln -s /usr/share/cmake/geographiclib/FindGeographicLib.cmake /usr/share/cmake-3.1*/Modules/
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      
      run: 
        mkdir /home/runner/work/vanetza/vanetza/build
        cd /home/runner/work/vanetza/vanetza/build 
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
